import { AppPropsType } from 'next/dist/shared/lib/utils';
import Head from 'next/head';
import '../styles/globals.css';

function MyApp({ Component, pageProps }: AppPropsType): JSX.Element {
  return (
    <>
      <Head>
        <title>OWL top</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Component {...pageProps} />
    </>
  )
}

export default MyApp;
